/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Arthur Ydalgo",
  "tagline": "An Inertia-styled monolith with Next.js' file-based routing system and file conventions for Vue and React",
  "url": "https://laravext.dev",
  "baseUrl": "/",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "throw",
  "favicon": "images/favicon.ico",
  "organizationName": "ArthurYdalgo",
  "projectName": "laravext",
  "themeConfig": {
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "metadata": [
      {
        "name": "og:image",
        "content": "https://laravext.dev/images/og_image.png"
      }
    ],
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "title": "ArthurYdalgo",
      "logo": {
        "alt": "Laravext Logo",
        "src": "images/logo.png"
      },
      "items": [
        {
          "position": "left",
          "to": "/projects",
          "label": "Projects"
        },
        {
          "position": "left",
          "to": "/resume",
          "label": "Resume"
        },
        {
          "href": "https://github.com/ArthurYdalgo/ArthurYdalgo",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Links",
          "items": [
            {
              "label": "LinkedIn",
              "href": "https://linkedin.com/in/arthur-y"
            },
            {
              "label": "TopTal Profile",
              "href": "https://www.toptal.com/resume/arthur-de-aguiar-ydalgo-miranda-couto"
            },
            {
              "label": "GitHub",
              "href": "https://www.github.com/ArthurYdalgo/ArthurYdalgo"
            }
          ]
        }
      ]
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "php",
        "toml",
        "jsx",
        "json"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "theme": {
          "customCss": [
            "./src/css/custom.css"
          ]
        },
        "docs": {
          "path": "docs",
          "sidebarPath": "/Users/arthurcouto/Documents/GitHub/ydalgo/sidebars/docs.js",
          "editUrl": "https://github.com/ArthurYdalgo/laravext/blob/master/docs/",
          "routeBasePath": "/"
        },
        "blog": {
          "path": "blog",
          "blogTitle": "Laravext Blog",
          "editUrl": "https://github.com/ArthurYdalgo/laravext/blob/master/docs/"
        },
        "pages": {}
      }
    ]
  ],
  "plugins": [
    "/Users/arthurcouto/Documents/GitHub/ydalgo/node_modules/docusaurus-lunr-search/src/index.js",
    "docusaurus-plugin-sass",
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "community",
        "path": "community",
        "sidebarPath": "/Users/arthurcouto/Documents/GitHub/ydalgo/sidebars/community.js",
        "routeBasePath": "/community",
        "editUrl": "https://github.com/ArthurYdalgo/laravext/blob/master/docs/"
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
